export const DECK_KEY = 'app:deck';

export const defaultDeck = {
  sampleDeck1:{
    title:'sampleDeck1',
    cards:[
      {
        question:'sampleQuestion1',
        answer:'sampleAnswer1'
      },
      {
        question:'sampleQuestion2',
        answer:'sampleAnswer12'
      }
    ]
  },
  sampleDeck2:{
    title:'sampleDeck2',
    cards:[
      {
        question:'sampleQuestion1',
        answer:'sampleAnswer1'
      },
      {
        question:'sampleQuestion2',
        answer:'sampleAnswer12'
      }
    ]
  },
  sampleDeck3:{
    title:'sampleDeck1',
    cards:[
      {
        question:'sampleQuestion1',
        answer:'sampleAnswer1'
      },
      {
        question:'sampleQuestion2',
        answer:'sampleAnswer12'
      }
    ]
  },
  sampleDeck4:{
    title:'sampleDeck1',
    cards:[
      {
        question:'sampleQuestion1',
        answer:'sampleAnswer1'
      },
      {
        question:'sampleQuestion2',
        answer:'sampleAnswer12'
      }
    ]
  },
  sampleDeck5:{
    title:'sampleDeck1',
    cards:[
      {
        question:'sampleQuestion1',
        answer:'sampleAnswer1'
      },
      {
        question:'sampleQuestion2',
        answer:'sampleAnswer12'
      }
    ]
  },
  sampleDeck6:{
    title:'sampleDeck1',
    cards:[
      {
        question:'sampleQuestion1',
        answer:'sampleAnswer1'
      },
      {
        question:'sampleQuestion2',
        answer:'sampleAnswer12'
      }
    ]
  },
  sampleDeck7:{
    title:'sampleDeck1',
    cards:[
      {
        question:'sampleQuestion1',
        answer:'sampleAnswer1'
      },
      {
        question:'sampleQuestion2',
        answer:'sampleAnswer12'
      }
    ]
  }
};
